kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redeployer-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets", "deployments"]
  verbs: ["get", "list", "watch", "patch"]
